### ISSUE TITLE
Is separation of short term and long term transactions needed?

### ISSUE THREAD

**Issue by kevinpark1217** [kevinpark1217/Robinhood-1099-Parser#1]
Currently the parser combines short term and long term transactions "for covered tax lots" into a single csv file.

Should I add the feature of separating them into 2 separate csv files?
How useful would this be?

**Comment by amzawisza** [comment]
It could be, it depends on the tax software being used.

**Comment by kevinpark1217** [comment]
Doesn't seem like an important feature to be added.
Closing the issue for right now...
