### ISSUE TITLE
Help running script

### ISSUE THREAD

**Issue by D-C-1977** [kevinpark1217/Robinhood-1099-Parser#11]
Hi, 
I am completely new to python script and have been trying to figure out how to get this to run. 
I am currently running python on  mac. I was able to run python3 -m pip install wheel and -m pip install --upgrade rh_1099 
but from here I am entirely confused where to go to execute and import my pdf file. 
Any help would be greatly appreciated!
Thank you! # #

**Comment by kevinpark1217** [comment]
Once installed, try running
```
rh_1099 --pdf <path_to_pdf> --check
```

For example,
```
rh_1099 --pdf ~/Downloads/robinhood_1099.pdf --check
```

**Comment by D-C-1977** [comment]
@kevinpark1217  

Thank you! This script was a life saver! Much appreciated!
