### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by hypnotizd** [kevinpark1217/Robinhood-1099-Parser#2]
Hey, I'm checking out your script and after getting git, python and visual studio build tools installed I finally got it to work. Now when I run the script, it errors out with index out of range. This is using the February 2021 RH pdf.

C:\Users\hypno\Documents\Robinhood-1099-Parser>python main.py --pdf 1099.pdf --check
Pages: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:04<00:00,  2.02it/s]
Traceback (most recent call last):
  File "C:\Users\hypno\Documents\Robinhood-1099-Parser\main.py", line 32, in <module>
    contents = parser.process(not args.silent)
  File "C:\Users\hypno\Documents\Robinhood-1099-Parser\rh_1099\pdf_parser\parser_2020.py", line 49, in process
    pdf_contents.add_sales(Sales2020.parse(last_raw_entries))
  File "C:\Users\hypno\Documents\Robinhood-1099-Parser\rh_1099\sales_transactions\sales_2020.py", line 38, in parse
    desc = raw_data[0].strip()
IndexError: list index out of range

**Comment by kevinpark1217** [comment]
Just to make sure, are you running from the latest commit?
If you don't know how to check this, run `git log -n 1` and paste the output here.

**Comment by hypnotizd** [comment]
Yes, it was a git from this morning shortly before I filed the bug report. Here is the output as requested:

C:\Users\hypno\Documents\Robinhood-1099-Parser>git log -n 1
commit 97533abdb2f1823e4a73be4091ebbff45c7c44ff (HEAD -> master, origin/master, origin/HEAD)
Author: Kevin Park <kevin.park1217@gmail.com>
Date:   Thu Mar 11 23:35:30 2021 -0500

    Bug fix: In the long term transaction sections...
    the strings in 'additional information' columns can be further fragmented

C:\Users\hypno\Documents\Robinhood-1099-Parser>

**Comment by kevinpark1217** [comment]
Can you try again with code in branch `bugfix_#2`?

You can test this by doing
```bash
git checkout bugfix_#2
python main.py .... # your command
```

Let me know if this fixes the problem.

**Comment by hypnotizd** [comment]
Missed a step there, needed to do a git fetch first. I figured it out though :) So with bugfix_#2 we get further, but it doesn't calculate the correct values and still errors:

C:\Users\hypno\Documents\Robinhood-1099-Parser>git fetch
remote: Enumerating objects: 13, done.
remote: Counting objects: 100% (13/13), done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 7 (delta 5), reused 7 (delta 5), pack-reused 0
Unpacking objects: 100% (7/7), 679 bytes | 21.00 KiB/s, done.
From https://github.com/kevinpark1217/Robinhood-1099-Parser
 * [new branch]      bugfix_#2  -> origin/bugfix_#2

C:\Users\hypno\Documents\Robinhood-1099-Parser>git checkout bugfix_#2
Switched to a new branch 'bugfix_#2'
Branch 'bugfix_#2' set up to track remote branch 'bugfix_#2' from 'origin'.

C:\Users\hypno\Documents\Robinhood-1099-Parser>python main.py --pdf 1099.pdf --check
Pages: 100%|█████████████████████████████████████████████████████████████████████████████| 9/9 [00:03<00:00,  2.26it/s]
>>> Calculated Totals:
    Make sure the values matches with the PDF totals!
    proceeds: 0.00, cost: 0.00, wash_sales_loss: 0.00, gain_loss: 0.00
Traceback (most recent call last):
  File "C:\Users\hypno\Documents\Robinhood-1099-Parser\main.py", line 48, in <module>
    contents.to_csv(args.csv)
  File "C:\Users\hypno\Documents\Robinhood-1099-Parser\rh_1099\pdf_contents.py", line 33, in to_csv
    writer.writerow(self.sales[0].columns)
IndexError: list index out of range

C:\Users\hypno\Documents\Robinhood-1099-Parser>

**Comment by kevinpark1217** [comment]
Hmm if that errors there, then it **might** mean that your PDF doesn't contain anything to report for taxes. But I do want to make sure that I don't miss anything.

Would you mind emailing your pdf to me? Or can you take screenshots with identifying information removed?
- I don't need to see the first 2 pages of the document
- Cover up the account number on the top right corner on pages containing transactions

You don't have to, but it is very odd that the parser is not detecting any transaction entry that needs to be reported.

**Comment by hypnotizd** [comment]
Okay, maybe that's my fault for thinking this would parse P/L and export to a spreadsheet instead of looking for something specific. Instead of me sending you my PDF would it be possible for you to explain what the section is that it's looking for so I can see if it's in my pdf? Otherwise taking 7 screenshots and editing them is a hassle.

**Comment by hypnotizd** [comment]
The PDF I'm using is "Account History" from February 2021. Not a 1099. Not sure why I thought this would work with it.🤦🏻‍♂️

**Comment by kevinpark1217** [comment]
This tool parses individual transactions into Excel file. By that it's looking for sections under "Proceeds from Broker and Barter Exchange Transactions" which should contain subsections that says "Short Term Transactions..." or "Long Term Transactions..."

If you're looking to parse just the summary, this tool doesn't do that, since it's pretty easy to do that by hand.

Latest commit in branch `bugfix_#2` should fix the error-ing out now.

**Comment by kevinpark1217** [comment]
> 
> The PDF I'm using is "Account History" from February 2021. Not a 1099. Not sure why I thought this would work with it.🤦🏻‍♂️

Oh okay. Yea this tool is only for 1099 documents from Robinhood, not just account history. That's why it doesn't work haha.

**Comment by hypnotizd** [comment]
Well when 2021 tax season comes around I have this bookmarked ;) Sorry for wasting your time!
