### ISSUE TITLE
How do you run this script?

### ISSUE THREAD

**Issue by DrBobSwagger** [kevinpark1217/Robinhood-1099-Parser#5]
I'm a python newb and don't know how to execute the script (or what directory to be in to execute). Thanks!

**Comment by kevinpark1217** [comment]
Could you give me more details?

How far are you on the installation instructions?
Which operating system are you running?

**Comment by DrBobSwagger** [comment]
Hey Kevin,

I just got it working on my Mac, had to specifically run python3 -m pip install wheel and python3 -m pip install --upgrade rh_1099

and call out python3. Thanks for the great code! It parsed my 1099 beautifully.

Karthic

**Comment by DrBobSwagger** [comment]
Feel free to close this, fixed it by calling out python3 in the install section. Thanks!
