### ISSUE TITLE
Totals are calculating incorrectly. 

### ISSUE THREAD

**Issue by maximumhax** [kevinpark1217/Robinhood-1099-Parser#6]
Everything ran fine, but the totals are not correct. proceeds, cost, wash and gain all wrong, gain is only off by $0.43, wash is about half the value it should be, and proceeds and cost is off quite a bit. Was really hoping this would work!! Taxes are almost due!

**Comment by maximumhax** [comment]
If you need my pdf you can message me directly if that would help. Thanks.

**Comment by kevinpark1217** [comment]
Ahh you shouldn't have waited until the last moment.  
This parser combines short term and long term totals together.  
So check that first.

If it is still wrong, you can email me with the pdf if you're okay with it

**Comment by kevinpark1217** [comment]
Since there hasn't been any update to this issue. I'm going to assume it's been resolved and close it
