### ISSUE TITLE
1200+ transactions missing from csv output

### ISSUE THREAD

**Issue by twangodev** [kevinpark1217/Robinhood-1099-Parser#7]
In total, I have 3235 transactions for a specific stock (listed on my 1099 tax form), but around 1200 is missing on the csv form (this affects my total proceeds calculation by a large amount). Everything else under 1000 transactions works fine though.

**Comment by twangodev** [comment]
If you need the PDF/CSV I would be happy to send them to you.

**Comment by kevinpark1217** [comment]
Yup, can you please email me the PDF?
There might be some differences that I may have not accounted for.

**Comment by twangodev** [comment]
Update: It was a miscalculation on my end, the CSV file had it located 4000+ lines away (but still there)
